version: "3.8"

services:
  booking-app:
    build: .
    ports:
      - "127.0.0.1:3002:3000"
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - default
      - deploy_default

networks:
  default:
    driver: bridge
  deploy_default:
    external: true
